version: '3.8'

services:
    prod:
        container_name: nestjs_api_prod
        image: nestjs-image
        env_file:
            - .env
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - ${PORT}:${PORT}
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    postgres:
        container_name: postgres-container
        image: postgres-image
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./DockerfilePg
        ports:
            - ${PORT_DB}:${PORT_DB}
        networks:
            - nesjs-network
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${PASSWORD_DB}
            POSTGRES_USER: ${USERNAME_DB}
            POSTGRES_DB: ${DB_NAME}
            PG_DATA: /var/lib/postgresql/data
networks:
    nesjs-network: